name: Fetch RSS and Update Posts

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Fetch RSS and Update JSON
        run: python fetch_rss.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add public/data/posts.json
          git commit -m "🔄 Auto-update posts.json with latest RSS data" || echo "No changes to commit"
          git push
